### ISSUE TITLE
where is BiFPN_Concat2 and BiFPN_Concat3?

### ISSUE THREAD

**Issue by Emma-qv** [LuYang-2023/ICMA2024#1]
Excuse me, I did not find BiFPN_Concat2 and BiFPN_Concat3 in ./models/common.py . And I did not find them in this project as well.

**Comment by LuYang-2023** [comment]
Hello! Thank you very much for your question. Indeed, the IDD-YOLOv5 model does not utilize the BiFPN_Concat2 and BiFPN_Concat3 components. In the models/IDD-YOLOv5.yaml file, we mainly use lightweight structures such as GhostConv, C3Ghost, and GSConv, along with the CARAFE module for feature fusion and processing, without adopting the BiFPN architecture. You can find the code for the GhostConv, C3Ghost, GSConv, and CARAFE modules in models/common.py. @Emma-qv

**Comment by Emma-qv** [comment]
Thank you for answering my question! But I found that BiFPN_Concat2 and BiFPN_Concat3 components were imported in train.py. And maybe this project also loses some other components, such as utils. Datasets', 'utils.general import check_img_size' and 'utils.loggers.wandb.wandb_utils import check_wandb_resume'.  <img width="1156" alt="截屏2024-09-12 17 27 04" src="https://github.com/user-attachments/assets/9f0710d3-a76d-4413-a77f-378e94639661">

**Comment by LuYang-2023** [comment]
Thank you for pointing this out. It seems there was an oversight in my previous uploads. I will update the repository immediately to address these issues. The missing components in the train.py and other parts of the project, like the utils module, will be properly included in the updated version. Please check back soon for the corrected files. I appreciate your patience and your help in improving the project! @Emma-qv

**Comment by LuYang-2023** [comment]
I have updated the relevant code, and you can refer to the YOLOv5 source code for specific details of the model configuration. Thank you for your patience and understanding as we strive to improve our project. If you encounter any issues or have further questions, please feel free to reach out. @Emma-qv

**Comment by Emma-qv** [comment]
Got it. Thank you!
